#!/usr/bin/env node
// Reads public/participants.csv, hits the local /api/linkedin endpoint for each
// LinkedIn URL, and writes app/lib/participants.seed.ts with the enriched roster.
// Requires `npm run dev` to be running on http://localhost:3000.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const CSV_PATH = join(ROOT, "public", "participants.csv");
const OUT_PATH = join(ROOT, "app", "lib", "participants.seed.ts");
const API_URL = process.env.API_URL || "http://localhost:3000/api/linkedin";
const CONCURRENCY = 4;

function extractSlug(url) {
  const m = url.match(/linkedin\.com\/in\/([^/?#]+)/i);
  return m ? decodeURIComponent(m[1]) : url;
}

function parseCsv(text) {
  const lines = text.split(/\r?\n/).filter((l) => l.trim().length > 0);
  if (lines.length === 0) return [];
  const [, ...rows] = lines;
  return rows.map((line) => {
    const cells = line.split(",");
    const name = (cells[0] || "").trim();
    const phone = (cells[1] || "").trim();
    const linkedinUrl = (cells[2] || "").trim();
    const slug = extractSlug(linkedinUrl);
    return {
      id: `li_${slug}`,
      name,
      handle: `@${slug}`,
      city: "",
      ...(phone ? { phone } : {}),
      ...(linkedinUrl ? { linkedinUrl } : {}),
    };
  });
}

function enrichPerson(base, profile) {
  const first = (profile.firstName || "").trim();
  const last = (profile.lastName || "").trim();
  const apiName = `${first} ${last}`.trim();
  const position = profile.position?.[0];
  const out = {
    ...base,
    name: apiName || base.name,
    city: profile.geo?.city || profile.geo?.country || base.city,
    enriched: true,
  };
  if (profile.headline) out.headline = profile.headline;
  if (profile.profilePicture) out.profilePicture = profile.profilePicture;
  if (position?.companyName) out.company = position.companyName;
  if (position?.title) out.title = position.title;
  return out;
}

async function fetchOne(person) {
  if (!person.linkedinUrl) return { person, ok: false, reason: "no-url" };
  try {
    const res = await fetch(API_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ url: person.linkedinUrl }),
    });
    if (!res.ok) {
      const body = await res.text().catch(() => "");
      return { person, ok: false, reason: `HTTP ${res.status} ${body.slice(0, 120)}` };
    }
    const data = await res.json();
    return { person: enrichPerson(person, data), ok: true };
  } catch (e) {
    return { person, ok: false, reason: e.message };
  }
}

async function main() {
  const csv = readFileSync(CSV_PATH, "utf8");
  const base = parseCsv(csv);
  console.log(`Loaded ${base.length} participants from CSV.`);

  const results = new Array(base.length);
  let done = 0;
  let ok = 0;
  let skip = 0;
  let fail = 0;
  const queue = base.map((p, i) => ({ p, i }));

  async function worker() {
    while (queue.length) {
      const task = queue.shift();
      if (!task) return;
      const r = await fetchOne(task.p);
      results[task.i] = r.person;
      done++;
      if (r.ok) ok++;
      else if (r.reason === "no-url") skip++;
      else {
        fail++;
        console.warn(`  ✗ ${task.p.name}: ${r.reason}`);
      }
      process.stdout.write(`\r[${done}/${base.length}] ok=${ok} skip=${skip} fail=${fail}   `);
    }
  }

  await Promise.all(Array.from({ length: CONCURRENCY }, worker));
  process.stdout.write("\n");

  const body =
    `import type { Person } from "./data";\n\n` +
    `// Generated by scripts/build-seed.mjs on ${new Date().toISOString()}.\n` +
    `// ${base.length} participants, ${ok} enriched, ${skip} skipped, ${fail} failed.\n` +
    `export const PARTICIPANTS_SEED: Person[] = ${JSON.stringify(results, null, 2)};\n`;

  writeFileSync(OUT_PATH, body);
  console.log(`Wrote ${OUT_PATH}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
